name: gotham-spectral-pipeline-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - ipympl
  - austin
  - pyink
  - mypy
  - loguru
  - pandas
  - pandas-stubs
  - astropy
  - numpy
  - scipy
  - bottleneck
  - sortedcontainers
